mountDir: "/home/shpark"
outputDir: "/home/shpark/tmp"
clusterName: "cluster"
testMode: true
elasticSearch:
  host: "3.37.79.125"
  port: "9200"
  indexName: es_log
skipDays:
- "Sunday"
jobs:
- day: "Wednesday"
  targets:
  - type: personal
    location: ps
    jobType: subDirs
  - type: project
    jobType: subDirs
    location: eks-an2-bee-st
  - type: global
    location: shared/webostv
    jobType: singleDir
  - type: global
    location: shared/dockrfiles
    jobType: singleDir
- day: "Everyday"
  targets:
  - type: personal
    jobType: subDirs
    location: shell
- day: "Everyday"
  targets:
  # - type: global
  #   location: ts/helmTest
  #   jobType: singleDir
  # - jobType: subDirs
  #   type: global
  #   location: ts
  #   skipDirs:
  #   - npd
  #   - operator
  #   - test
  #   - node-mon-deploy
  #   - helmTest
  # - type: personal
  #   jobType: subDirs
  #   location: golang
  #   skipDirs:
  #   - src
  - type: project
    location: golang/src/github.com/ShaunPark
    jobType: subDirs
